spring:
  datasource:
    url: jdbc:mysql://localhost:53306/example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  batch:
    jdbc:
      platform: mysql
    job:
      enabled: true
      names:
